# Generated by Django 3.2.18 on 2023-02-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.IntegerField()),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("picture", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
