# Generated by Django 3.2.18 on 2023-02-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0002_alter_character_character_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="character_id",
            field=models.IntegerField(),
        ),
    ]
